name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Verify installed packages
        run: |
          pip show black
          pip show ruff

      - name: Run Black to check formatting
        run: |
          black --check .
        continue-on-error: true  # Optional: Continue even if Black finds issues

      - name: Run Ruff for linting
        run: |
          ruff .
        continue-on-error: true  # Optional: Continue even if Ruff finds issues
